<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<AssemblyName>VipNameChecker</AssemblyName>
		<RootNamespace>VipNameChecker</RootNamespace>
		<Version>1.2.0.0</Version>

		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>

		<DevPluginOutputPath Condition="'$(DevPluginOutputPath)' == ''">$(AppData)\XIVLauncher\devPluginOutputs\VipNameChecker\</DevPluginOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<None Update="VipNameChecker.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="CopyToDevPluginOutput" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug' AND '$(DevPluginOutputPath)' != ''">
		<MakeDir Directories="$(DevPluginOutputPath)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DevPluginOutputPath)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(TargetDir)$(AssemblyName).json" DestinationFolder="$(DevPluginOutputPath)" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)$(AssemblyName).json')" />
	</Target>
</Project>